joke Site practice/Models/Joke.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace joke_Site_practice.Models
{
	public class Joke
	{
		public int Id { get; set; }
		public string JokeQuestion { get; set; }
		public string JokeAnswer { get; set; }
		public string JokeUserId { get; set; }
		public string JokeEmail { get; set; }
		

	}

}

joke Site practice/Controllers/HomeController.cs
using joke_Site_practice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace joke_Site_practice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

joke Site practice/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using joke_Site_practice.Models;
using joke_Site_practice.Data;
using joke_Site_practice.Authorization;
using Microsoft.AspNetCore.Authorization;


namespace joke_Site_practice.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;
        protected IAuthorizationService AuthorizationService { get; }
        protected UserManager<IdentityUser> UserManager { get; }

        public JokesController(ApplicationDbContext context,
            IAuthorizationService authorizationService,
            UserManager<IdentityUser> userManager) : base()
        {
            _context = context;
            UserManager = userManager;
            AuthorizationService = authorizationService;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Joke.ToListAsync());
        }

        // GET: Jokes/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST: Jokes/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index",await _context.Joke.Where( j => j.JokeQuestion.Contains(SearchPhrase) ).ToListAsync()); ;
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // GET: Jokes/Create

        public IActionResult Create()
        {
            return View();
        }
        public Joke Joke { get; set; }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JokeQuestion,JokeAnswer")] Joke joke)
        {
            if (!ModelState.IsValid)
            {
                return View(joke);
            }
            joke.JokeUserId = UserManager.GetUserId(User);
            joke.JokeEmail = UserManager.GetUserName(User);

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, joke, JokeOperations.Create);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }
            _context.Add(joke);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
        }

        // GET: Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var joke = await _context.Joke.FindAsync(id);

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, joke, JokeOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokeQuestion,JokeAnswer,JokeUserId")] Joke joke)
        {
            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, joke, JokeOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            if (id != joke.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joke);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeExists(joke.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Jokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {


            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, joke, JokeOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }

            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // POST: Jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var joke = await _context.Joke.FindAsync(id);
            _context.Joke.Remove(joke);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
            return _context.Joke.Any(e => e.Id == id);
        }
    }
}

joke Site practice/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Welcome to my .NET Web Core Practice Site, It is not patricually complex and more of a learning platform to improve my skills.</p>
</div>

joke Site practice/Views/Jokes/Create.cshtml
@model joke_Site_practice.Models.Joke

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JokeQuestion" class="control-label"></label>
                <input asp-for="JokeQuestion" class="form-control" />
                <span asp-validation-for="JokeQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeAnswer" class="control-label"></label>
                <input asp-for="JokeAnswer" class="form-control" />
                <span asp-validation-for="JokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

joke Site practice/Views/Jokes/Delete.cshtml
@model joke_Site_practice.Models.Joke

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Joke</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JokeQuestion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JokeQuestion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JokeAnswer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JokeAnswer)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

joke Site practice/Views/Jokes/Details.cshtml
@model joke_Site_practice.Models.Joke

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Joke</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JokeQuestion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JokeQuestion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JokeAnswer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JokeAnswer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JokeUserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JokeUserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

joke Site practice/Views/Jokes/Edit.cshtml
@model joke_Site_practice.Models.Joke

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="JokeUserId" />
            <div class="form-group">
                <label asp-for="JokeQuestion" class="control-label"></label>
                <input asp-for="JokeQuestion" class="form-control" />
                <span asp-validation-for="JokeQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeAnswer" class="control-label"></label>
                <input asp-for="JokeAnswer" class="form-control" />
                <span asp-validation-for="JokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

joke Site practice/Views/Jokes/Index.cshtml
@model IEnumerable<joke_Site_practice.Models.Joke>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/Jokes_Index.css" />

<div class="Jokes_Index-Title">
    <h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
</div>

<table class="table">
@{int i=0;}
@foreach (var item in Model)
{

    <div id="accordion">
        <div class="card border border-primary">
            <div class="card-header" id="heading_@i">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse_@i" aria-expanded="false" aria-controls="collapse_@i">
                        @Html.DisplayFor(modelItem => item.JokeQuestion)
                    </button>
                </h5>
            </div>

            <div id="collapse_@i" class="collapse" aria-labelledby="heading_@i" data-parent="#accordion">
                <div class="card-body">
                    <div>
                        Answer:
                        @Html.DisplayFor(modelItem => item.JokeAnswer)
                    </div>
                    <div>
                        Username:
                        @if (item.JokeEmail != null) {
                        @(Html.DisplayFor(modelItem => item.JokeEmail))
                        } else {
                            <text> Null </text>
                        }
                    </div>
                    <div>
                        @if ((await AuthorizationService.AuthorizeAsync(User, item, JokeOperations.Update)).Succeeded)
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <text> | </text>
                        }

                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>

                        @if ((await AuthorizationService.AuthorizeAsync(User, item, JokeOperations.Delete)).Succeeded)
                        {
                            <text> | </text>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        }

                    </div>

                </div>
            </div>
        </div>
    </div>
    i++;
}
</table>

joke Site practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - joke_Site_practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">joke_Site_practice</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom mb-3">
            <div class="container">

                <form class="form-inline" asp-controller="Jokes" asp-action="ShowSearchResults">
                    <div class="input-group mb-3">
                        <input name="SearchPhrase" class="form-control" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit">Search</button>
                        </div>
                    </div>
                </form>

            </div>

        </nav>



    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>